# Generated by Django 3.2.13 on 2022-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220806_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.AddField(
            model_name='news',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
