# Generated by Django 3.2.13 on 2022-08-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20220806_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='viewCount',
            new_name='view_count',
        ),
    ]
